version: '3.8'

services:
  product-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - WORKERS=5
      - QUEUE_SIZE=2000
      - PORT=8080
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - product-network

networks:
  product-network:
    driver: bridge
